# Generated by Django 2.0.5 on 2019-07-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
